language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    include:
        - rust: stable
          env: TARGET=test
        - rust: beta
          env: TARGET=test
        - rust: nightly
          env: TARGET=bench

script: make $TARGET
